// Code generated by MockGen. DO NOT EDIT.
// Source: app/controller/controller.go

// Package mock_controller is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	"go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
        ctrl     *gomock.Controller
        recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
        mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
        mock := &MockController{ctrl: ctrl}
        mock.recorder = &MockControllerMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
        return m.recorder
}

// FindAllBrands mocks base method.
func (m *MockController) FindAllBrands(w http.ResponseWriter, r *http.Request) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "FindAllBrands", w, r)
}

// FindAllBrands indicates an expected call of FindAllBrands.
func (mr *MockControllerMockRecorder) FindAllBrands(w, r interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllBrands", reflect.TypeOf((*MockController)(nil).FindAllBrands), w, r)
}

// FindAllBrandsByDescription mocks base method.
func (m *MockController) FindAllBrandsByDescription(w http.ResponseWriter, r *http.Request) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "FindAllBrandsByDescription", w, r)
}

// FindAllBrandsByDescription indicates an expected call of FindAllBrandsByDescription.
func (mr *MockControllerMockRecorder) FindAllBrandsByDescription(w, r interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllBrandsByDescription", reflect.TypeOf((*MockController)(nil).FindAllBrandsByDescription), w, r)
}

// FindBrandById mocks base method.
func (m *MockController) FindBrandById(w http.ResponseWriter, r *http.Request) {
        m.ctrl.T.Helper()
        m.ctrl.Call(m, "FindBrandById", w, r)
}

// FindBrandById indicates an expected call of FindBrandById.
func (mr *MockControllerMockRecorder) FindBrandById(w, r interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBrandById", reflect.TypeOf((*MockController)(nil).FindBrandById), w, r)
}