-- +goose Up
INSERT INTO brand (description, created_at) VALUES ('1906', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('3 Corações', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('3M', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('51', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('61 Emi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('88', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Absolut', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Actimel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Activia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Adocyl', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Adria', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Adultmax', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Affinity', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Air Wick', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ajax', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Aladdin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Alfaparf', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Aliança', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Alklin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Allmix', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Altos Del Plata', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Amarula', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Amazônia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Amélia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ana Maria', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Aperol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Apreciare', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Arcor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Arisco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Arqplast', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Asahi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Assolan', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Aurora', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Aviação', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Axe', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Aymoré', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Baby Looney Tunes', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bacardi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Baconzitos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Baden Baden', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ballantine''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Barilla', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Barion', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Baruel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bauducco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bebê Natureza', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Beefeater', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bell''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Belvita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bettanin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bigfral', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Billa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Biotropic Cosmética', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Black Princess', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Black Stone', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Blue Diamond', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bolete', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bolla', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bom Bril', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bom Destino', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bomguy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bon Gouter', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bonduelle', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Boni Baby', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Boni Kids', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Boni Natural', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bonoarroz', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Bonomilho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Borges', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Brasinha', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Brasso', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Brigitta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Brilhante', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Britânia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Caboclo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cacildis', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Café 3 Poderes', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Café Assum Preto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Café Brasileiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Café Do Cê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Café Rancheiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Café do Sítio', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Campari', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Campo Largo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Candy Fun', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Caninha da Roça', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Carbonell', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cardeal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Carefree', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Carreiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Casa Km', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Casa Madeira', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Casa Suíça', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Casa de Bento', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Casal Garcia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Catupiry', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cebolitos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Chamex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Champ', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Chandon', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cheetos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Chimarrão dos Pampas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Chivas Regal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Chá Leão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cica', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cif', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cinderela', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cinzano', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Clear', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cless', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Clight', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Closeup', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Club Social', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Coala', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Coco do Vale', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cocolândia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cointreau', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Colgate', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Collina Del Sole', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Colorado', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Comary', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Comfort', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('CompLeite', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Conde de Foucauld', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Contini', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Copag', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Copra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Coqueiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Coquetel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Corote', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Corpus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cotton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Country Wine', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cremer', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cremosy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Crystal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Cynar', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dafruta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Danette', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Danio', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Danone', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Danoninho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Darling', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Davene', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Delakasa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Deluxe', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Delícia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Depi Roll', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Destac', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dicasa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dimension', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dimy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Disqueti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Do Bem', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Doce Vida', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Doces São Lourenço', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dom José', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Domecq', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Domus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dona Benta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dona Clara', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dona Cota', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dori', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Doritos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dove', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dreamies', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dreher', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Drury''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dualette', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ducoco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Duetto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dunhill', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Dushy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Easy-Off', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Eisenbahn', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Elefante', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Elite', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Elma Chips', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Eqlibri', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Esporão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Estrela', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Estrella Galicia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Etti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Faber-Castell', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Faixa Azul', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Fama', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Famiglia Venturelli', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Faxe', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Feelclean', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ferrero Collection', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ferrero Rocher', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Festiva', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Fiat Lux', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Finish', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Finn', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Flor de Algodão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Flor de Ypê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Fofo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Fort', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Fortaleza', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Força Azul', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Fresh', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Frimesa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Frisco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Frutap', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Frutapinho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Frutilac', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('GB', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Gallo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Galo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Gato Negro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Gaúcho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Gina', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Globo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Gogó', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Goodie', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Gordon''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Gourmet', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Gran Mestri', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Granado', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Grand Old Parr', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Grandes Marcas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Grant''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Grape Cool', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Grey Goose', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Guara Viton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Guigui', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Halls', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Harpic', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Hart''s Natural', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Hellmann''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Hercules', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Herdade do Esporão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Hershey''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Herói', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Hiper', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Houston', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Huggies', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Hué', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ice Cola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('IceFresh', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Iguaçu', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Intimus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Io-Iô', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Iphigeny Kosmetic', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Iracema', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ironage', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Isoeste', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Itacolomy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Itaipava', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Itaipava Premium', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Itajá', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('J&B', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Jandaia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Jasmine', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Johnnie Walker', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Johnson''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Johnson''s Baby', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Jose Cuervo Especial', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Jun Daiti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kalipto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Karo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Katbom', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Keeprend', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kellogg''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kellogg''s Corn Flakes', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kero Coco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kibon', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kicaldo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kimimo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kiss', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kitano', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kitchen', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kleenex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Knorr', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kobber', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Kosten', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('La Española', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('La Fruit', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('La Pastina', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Lacta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Latitud 33º', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Lay''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Leblon Soft Blanc', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Lebre', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('LeitBom', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Leite de Rosas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Leitíssimo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Leonoff', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Leão Fuze', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Liderança', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Liebfraumilch', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Lifebuoy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Limpol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Linea', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Lipton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Listerine', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Liza', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Loctite', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Logan', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Lolita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Looping', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Lunar', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Lux', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('M&M''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mabel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maggi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Magneto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Magnum', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maguary', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mais Vita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maizena', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maniacs', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maped', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maratá', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Marcus James', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maria', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Martini', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mascote', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Massas Paulista', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('MasterFoods', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Matacura', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Matte Leão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maxprint', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Maxton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Melitta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Menina', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Merilú', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mesa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mezzani', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Moinho Fino', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mon Bijou', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Montilla', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mortein', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Moët & Chandon', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mr. Bey', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Multilaser', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mumm', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mundial', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Muriel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Mãe Terra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Natasha', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Native', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Natu Nobilis', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Naturacitrus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Natural One', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Natural Tea', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nescafé', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nestlé', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Neutrogena', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Neve', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nigro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nikkoh', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nissin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nivea', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nivea Men', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nova Oliva', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Novex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nugget', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nutella', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nutrella', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nutry', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Nêga Fulô', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('OQ', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Obikwa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Old Eight', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Old Parr', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Olvebra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Olívia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Omo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Oremus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Oreo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Orloff', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ovomaltine', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pais & Filhos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Palmolive', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Palmolive Naturals', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Paloma', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pamplona', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Parmalat', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Parodontax', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Passe Bem', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Passport Scotch', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pato', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Paulista', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pedigree', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pelaggio', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Perfetto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Perfex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Periquita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Personal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Personal Soft & Protect', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Petra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Phebo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Philadelphia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pilar', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pilão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pinho Bril', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pinho Sol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pinho Urca', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pinho Ypê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Piquitucho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Piracanjuba', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Piraquê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Plenitud', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Plásticos Rischioto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Plásticos Santana', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Polak', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Poliflor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pom Pom', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pomarola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ponjita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Porca de Murça', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Positron', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Post-it', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pox', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pramesa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Prat''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pratice', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Predilecta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Primor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pritt', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Proauto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Procão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Proibida', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Protex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pullman', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pulsi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Puro Coco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pury Vitta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Pérgola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Q''Brilho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Qboa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Quaker', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Quality', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Queensberry', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Quinta do Morgado', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Raffaello', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Raiola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Rajska', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Rancheiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Rap 10', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Raposinha', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Real Multiervas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Red Hot', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Regatas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Renata', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Repelex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Rexona', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Rexona Clinical', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Rich''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Richester', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Rock''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Roma Brinquedos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Roots To Go', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Royal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ruffino', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ruth Care', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ráris', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('SBP', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sabor & Vida', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sacciali', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sagatiba', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Saint Germain', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Salada', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Salinas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Salsaretti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sangue de Boi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sanol Dog', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Santa Clara', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Santa Helena', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Santepel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sapeka', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sauza', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Schin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Scotch', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Scotch-Brite', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Scott', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Seagers', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Secalux', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Seda', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Semorin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sempre Livre', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sensodyne', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Serigy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Seven Boys', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sid-Nyl', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Silver Seagers', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Silvo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Simple', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Skarloff', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Skyy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Snickers', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Snob', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Social Clean', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sorriso', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Soya', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('St. Remy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Stella D''oro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Stock', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Stylus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Suave', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sun', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Superbom', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Supra Soy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Surf', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Suzano Report', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sym', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Syn', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('São Geraldo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('São João da Barra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('São Vicente', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Sítio', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('TNT', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Taiga', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Talisker', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tandy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tang', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tanqueray', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Teacher''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Terra Brazilis', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Therezópolis', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tic Tac', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ting', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tinindo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tio João', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tirol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tirolez', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tixan Ypê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Toblerone', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Toddy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Toddynho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Toscano', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Trapiche', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tres', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Tresemmé', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Trevinho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Trident', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Trim', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Twix', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ufe', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ultra Action', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ultra Corega', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Urbano', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Urca', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Usual Brinquedos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Vagisil', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Vale Fértil', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Vanish', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Vasenol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Veja', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Vigor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Vim', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Visconti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Vitao', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Vitarella', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('WD-40', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Wall Street', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Weihenstephaner', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Weltenburger Kloster', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Wheaton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Whiskas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('White Horse', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Wickbold', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Yakult', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Yakult 40', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Yamá', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Yogurte100', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Yoki', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ypióca', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ypê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Yuri Fit', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Zero Cal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Zinho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_at) VALUES ('Ápice', LOCALTIMESTAMP);