-- +goose Up
INSERT INTO brand (description, created_date) VALUES ('1906', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('3 Corações', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('3M', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('51', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('61 Emi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('88', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Absolut', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Actimel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Activia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Adocyl', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Adria', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Adultmax', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Affinity', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Air Wick', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ajax', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Aladdin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Alfaparf', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Aliança', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Alklin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Allmix', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Altos Del Plata', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Amarula', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Amazônia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Amélia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ana Maria', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Aperol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Apreciare', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Arcor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Arisco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Arqplast', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Asahi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Assolan', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Aurora', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Aviação', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Axe', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Aymoré', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Baby Looney Tunes', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bacardi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Baconzitos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Baden Baden', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ballantine''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Barilla', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Barion', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Baruel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bauducco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bebê Natureza', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Beefeater', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bell''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Belvita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bettanin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bigfral', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Billa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Biotropic Cosmética', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Black Princess', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Black Stone', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Blue Diamond', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bolete', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bolla', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bom Bril', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bom Destino', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bomguy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bon Gouter', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bonduelle', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Boni Baby', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Boni Kids', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Boni Natural', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bonoarroz', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Bonomilho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Borges', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Brasinha', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Brasso', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Brigitta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Brilhante', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Britânia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Caboclo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cacildis', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Café 3 Poderes', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Café Assum Preto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Café Brasileiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Café Do Cê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Café Rancheiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Café do Sítio', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Campari', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Campo Largo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Candy Fun', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Caninha da Roça', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cantina da Serra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Carbonell', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cardeal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Carefree', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Carreiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Casa Km', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Casa Madeira', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Casa Suíça', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Casa de Bento', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Casal Garcia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Catupiry', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cebolitos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Chamex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Champ', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Chandon', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cheetos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Chimarrão dos Pampas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Chivas Regal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Chá Leão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cica', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cif', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cinderela', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cinzano', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Clear', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cless', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Clight', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Closeup', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Club Social', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Coala', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Coco do Vale', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cocolândia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cointreau', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Colgate', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Collina Del Sole', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Colorado', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Comary', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Comfort', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('CompLeite', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Conde de Foucauld', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Contini', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Copag', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Copra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Coqueiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Coquetel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Corote', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Corpus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cotton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Country Wine', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cremer', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cremosy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Crystal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Cynar', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dafruta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Danette', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Danio', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Danone', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Danoninho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Darling', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Davene', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Delakasa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Deluxe', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Delícia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Depi Roll', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Destac', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dicasa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dimension', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dimy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Disqueti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Do Bem', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Doce Vida', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Doces São Lourenço', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dom José', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Domecq', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Domus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dona Benta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dona Clara', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dona Cota', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dori', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Doritos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dove', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dreamies', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dreher', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Drury''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dualette', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ducoco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Duetto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dunhill', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Dushy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Easy-Off', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Eisenbahn', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Elefante', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Elite', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Elma Chips', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Eqlibri', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Esporão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Estrela', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Estrella Galicia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Etti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Faber-Castell', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Faixa Azul', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Fama', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Famiglia Venturelli', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Faxe', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Feelclean', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ferrero Collection', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ferrero Rocher', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Festiva', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Fiat Lux', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Finish', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Finn', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Flor de Algodão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Flor de Ypê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Fofo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Forno de Minas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Fort', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Fortaleza', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Força Azul', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Fresh', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Frimesa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Frisco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Frutap', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Frutapinho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Frutilac', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('GB', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gallo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Galo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gato Negro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gaúcho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gina', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Globo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gogó', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gomes da Costa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Goodie', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gordon''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gourmet', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Gran Mestri', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Granado', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Grand Old Parr', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Grandes Marcas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Grant''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Grape Cool', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Grey Goose', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Guara Viton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Guigui', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('HairLife', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Halls', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Harpic', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Hart''s Natural', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Hellmann''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Hercules', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Herdade do Esporão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Hershey''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Herói', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Hiper', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Houston', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Huggies', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Hué', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ice Cola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('IceFresh', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Iguaçu', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Intimus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Io-Iô', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Iphigeny Kosmetic', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Iracema', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ironage', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Isoeste', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Itacolomy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Itaipava', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Itaipava Premium', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Itajá', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('J&B', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Jandaia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Jasmine', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Johnnie Walker', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Johnson''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Johnson''s Baby', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Jose Cuervo Especial', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Jun Daiti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kalipto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Karo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Katbom', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Keeprend', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kellogg''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kellogg''s Corn Flakes', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kero Coco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kibon', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kicaldo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kimimo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kiss', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kitano', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kitchen', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kleenex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Knorr', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kobber', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Kosten', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('La Española', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('La Fruit', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('La Pastina', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Lacta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Latitud 33º', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Lay''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Leblon Soft Blanc', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Lebre', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('LeitBom', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Leite de Rosas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Leitíssimo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Leonoff', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Leão Fuze', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Liderança', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Liebfraumilch', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Lifebuoy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Limpol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Linea', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Lipton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Listerine', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Liza', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Loctite', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Logan', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Lolita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Looping', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Lunar', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Lux', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('M&M''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mabel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maggi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Magneto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Magnum', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maguary', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mais Vita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maizena', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maniacs', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maped', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maratá', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Marcus James', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maria', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Martini', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mascote', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Massas Paulista', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('MasterFoods', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Matacura', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Matte Leão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maxprint', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Maxton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Melitta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Menina', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Merilú', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mesa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mezzani', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Moinho Fino', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mon Bijou', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Montilla', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mortein', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Moët & Chandon', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mr. Bey', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Multilaser', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mumm', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mundial', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Muriel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Mãe Terra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Natasha', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Native', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Natu Nobilis', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Naturacitrus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Natural One', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Natural Tea', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nescafé', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nestlé', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Neutrogena', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Neve', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nigro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nikkoh', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nissin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nivea', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nivea Men', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nova Oliva', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Novex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nugget', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nutella', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nutrella', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nutry', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Nêga Fulô', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('OQ', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Obikwa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Old Eight', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Old Parr', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Olvebra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Olívia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Omo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Oremus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Oreo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Orloff', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ovomaltine', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pais & Filhos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Palmolive', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Palmolive Naturals', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Paloma', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pamplona', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Parmalat', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Parodontax', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Passe Bem', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Passport Scotch', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pato', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Paulista', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pedigree', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pelaggio', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Perfetto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Perfex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Periquita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Personal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Personal Soft & Protect', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Petra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Phebo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Philadelphia', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pilar', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pilão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pinho Bril', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pinho Sol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pinho Urca', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pinho Ypê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Piquitucho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Piracanjuba', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Piraquê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Plenitud', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Plásticos Rischioto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Plásticos Santana', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Polak', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Poliflor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pom Pom', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pomarola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ponjita', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Porca de Murça', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Positron', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Post-it', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pox', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pramesa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Prat''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pratice', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Predilecta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Primor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pritt', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Proauto', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Procão', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Proibida', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Protex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pullman', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pulsi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Puro Coco', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pury Vitta', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Pérgola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Q''Brilho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Qboa', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Quaker', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Quality', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Queensberry', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Quinta do Morgado', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Raffaello', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Raiola', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Rajska', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Rancheiro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Rap 10', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Raposinha', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Real Multiervas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Red Hot', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Regatas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Renata', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Repelex', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Rexona', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Rexona Clinical', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Rich''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Richester', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Rock''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Roma Brinquedos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Roots To Go', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Royal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ruffino', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ruth Care', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ráris', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('SBP', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sabor & Vida', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sacciali', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sagatiba', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Saint Germain', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Salada', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Salinas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Salsaretti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sangue de Boi', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sanol Dog', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Santa Clara', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Santa Helena', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Santepel', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sapeka', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sauza', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Schin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Scotch', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Scotch-Brite', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Scott', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Seagers', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Secalux', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Seda', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Semorin', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sempre Livre', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sensodyne', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Serigy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Seven Boys', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sid-Nyl', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Silver Seagers', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Silvo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Simple', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Skarloff', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Skyy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Snickers', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Snob', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Social Clean', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sorriso', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Soya', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('St. Remy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Stella D''oro', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Stock', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Stylus', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Suave', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sun', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Superbom', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Supra Soy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Surf', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Suzano Report', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sym', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Syn', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('São Geraldo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('São João da Barra', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('São Vicente', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Sítio', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('TNT', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Taiga', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Talisker', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tandy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tang', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tanqueray', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Teacher''s', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Terra Brazilis', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Therezópolis', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tic Tac', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ting', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tinindo', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tio João', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tirol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tirolez', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tixan Ypê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Toblerone', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Toddy', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Toddynho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Toscano', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Trapiche', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tres', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Tresemmé', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Trevinho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Trident', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Trim', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Twix', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ufe', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ultra Action', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ultra Corega', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Urbano', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Urca', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Usual Brinquedos', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Vagisil', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Vale Fértil', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Vanish', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Vasenol', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Veja', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Vigor', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Vim', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Visconti', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Vitao', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Vitarella', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('WD-40', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Wall Street', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Weihenstephaner', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Weltenburger Kloster', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Wheaton', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Whiskas', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('White Horse', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Wickbold', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Yakult', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Yakult 40', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Yamá', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Yogurte100', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Yoki', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ypióca', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ypê', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Yuri Fit', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Zero Cal', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Zinho', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('keep Cooler', LOCALTIMESTAMP);
INSERT INTO brand (description, created_date) VALUES ('Ápice', LOCALTIMESTAMP);