server:
  name: "GShopping"
  version: "0.1"
  port: 4000

database:
  postgres:  
    db_host: ${DB_HOST}
    db_port: ${DB_PORT}
    db_user: ${DB_USER}
    db_pass: ${DB_PASS}
    db_name: ${DB_NAME}