FROM golang:1.20 AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /gshopping

FROM gcr.io/distroless/base-debian11

WORKDIR /
COPY --from=build /gshopping /gshopping
COPY --from=build /app/db/ /db
COPY --from=build /app/config.yml /config.yml
COPY --from=build /app/banner.txt /banner.txt
EXPOSE 4000
USER nonroot:nonroot

ENTRYPOINT ["/gshopping"]
