services:
  gshopping-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gshopping-api
    restart: always
    environment:
      - DB_HOST=gshopping-db
      - DB_PORT=45432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=gshopping
    ports:
      - "4000:4000"
    depends_on:
      - gshopping-db
    networks:
      - nginx-net
      - gshopping-net

  gshopping-db:
    build: 
      context: ./db/postgres
      dockerfile: Dockerfile
    container_name: gshopping-db
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    restart: always
    ports:
      - "45432:45432"
    environment:
      - POSTGRES_DB=gshopping
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - gshopping-net
    volumes:
      - ./db/.docker:/var/lib/postgresql/data
      - ./db/postgres/postgresql.conf:/etc/postgresql/postgresql.conf

networks:
  gshopping-net:
    driver: bridge
  nginx-net:
    driver: bridge
    name: nginx-net