name: Go Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Configurar GO
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
      
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Run tests
      run: go test ./...
